use_frameworks!

target 'MonsterNetworking_Example' do
  pod 'MonsterNetworking', :path => '../'
  pod 'SwiftyJSON'
  pod 'SnapKit'
  pod 'Kingfisher'
  pod 'Toaster'
  
  target 'MonsterNetworking_Tests' do
    inherit! :search_paths

    
  end
end
